# Generated by Django 3.0.4 on 2020-03-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
