# Generated by Django 3.0.4 on 2020-06-19 23:43

from django.db import migrations
import django_resized.forms
import functools
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[300, 300], upload_to=functools.partial(index.models._update_filename, *(), **{'path': 'images/'})),
        ),
    ]
