# Generated by Django 3.0.4 on 2020-03-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
