# Generated by Django 3.0.4 on 2020-03-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_meal_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
