# Generated by Django 3.0.4 on 2020-04-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20200330_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
