# Generated by Django 3.0.4 on 2020-04-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_meal_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cover',
            field=models.ImageField(null=True, upload_to='chefjess/images/'),
        ),
    ]
