# Generated by Django 3.0.4 on 2020-04-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20200401_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
