# Generated by Django 3.0.4 on 2020-04-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200401_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
