# Generated by Django 3.0.4 on 2020-04-02 16:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_meal_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='cover',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='images/'),
        ),
    ]
