# Generated by Django 3.0.4 on 2020-04-03 20:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20200402_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=0, size=[300, 300], upload_to='images/3ce03153-dbd7-4b86-8b6a-b5b3c0df1376'),
        ),
    ]
