# Generated by Django 3.0.4 on 2020-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_browser_operatingsystem_pageload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageload',
            name='user',
        ),
        migrations.AddField(
            model_name='pageload',
            name='meal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
